spring:
  application.:
    name: activity-service
  data:
    mongodb:
      uri: mongodb+srv://mohanroot12:mohanroot@cluster0.fwf7guy.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: fitness_activity
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking